module:
  admin_toolbar: 0
  adminimal_admin_toolbar: 0
  auto_entitylabel: 0
  autocomplete_deluxe: 0
  automated_cron: 0
  block: 0
  block_content: 0
  bootstrap_layouts: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  conditional_fields: 0
  config: 0
  config_update: 0
  contact: 0
  contextual: 0
  css_editor: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  features: 0
  features_ui: 0
  feeds: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  glia_glossary: 0
  google_analytics: 0
  help: 0
  history: 0
  image: 0
  kint: 0
  layout_discovery: 0
  link: 0
  login_emailusername: 0
  mailsystem: 0
  menu_ui: 0
  mimemail: 0
  multiple_selects: 0
  neuronet_misc: 0
  node: 0
  node_view_permissions: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  search: 0
  shortcut: 0
  switch_page_theme: 0
  system: 0
  taxonomy: 0
  taxonomy_manager: 0
  term_csv_export_import: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_bootstrap: 0
  views_bulk_operations: 0
  views_ef_fieldset: 0
  views_ui: 0
  ds: 1
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  adminimal_theme: 0
  bootstrap: 0
  yorkshire: 0
  material_admin: 0
  elevenfeat: 0
  eleven: 0
  neuronet_home: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
