format: full_html
name: NeuroNet
mail: stiso@pennmedicine.upenn.edu
linkonly: false
textonly: false
sitestyle: true
simple_address: false
engine: mimemail
preserve_class: false
advanced:
  incoming: false
  key: BGDz5kQHBlCnTK8OuiU78WE4D7YP1CevfvaqDLNEIbs
_core:
  default_config_hash: 7mRdLbI-Rda0ePrw4IkNSJd8m_lTx7nLZnVfbNbyfwA
